routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProductGalleryController;
use App\Http\Controllers\Admin\TransactionContoller;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DetailController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/categories', [CategoryController::class, 'index'])->name('categories');
Route::get('/categories/{id}', [CategoryController::class, 'detail'])->name('categories.detail');

Route::get('/details/{id}', [DetailController::class, 'index'])->name('detail');
Route::post('/details/{id}', [DetailController::class, 'add'])->name('detail.add');

Route::get('/success', [CartController::class, 'success'])->name('success');
Route::get('/register/success', [RegisterController::class, 'success'])->name('register.success');

Route::middleware(['auth'])->group(function () {
    Route::get('/cart', [CartController::class, 'index'])->name('cart');
    Route::delete('/cart/{id}', [CartController::class, 'delete'])->name('cart.delete');

    Route::post('/checkout', [CheckoutController::class, 'process'])->name('checkout');
    Route::post('/checkout/callback', [CheckoutController::class, 'callback'])->name('checkout.callback');
});

Route::prefix('dashboard')->middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('products', [DashboardController::class, 'products'])->name('dashboard.products');
    Route::get('products/create', [DashboardController::class, 'products_create'])->name('dashboard.products.create');
    Route::post('products/store', [DashboardController::class, 'products_store'])->name('dashboard.products.store');
    Route::get('products/{id}', [DashboardController::class, 'products_details'])->name('dashboard.products.details');
    Route::put('products/{id}', [DashboardController::class, 'products_update'])->name('dashboard.products.update');

    Route::post('products/gallery/upload', [DashboardController::class, 'upload_gallery'])->name('dashboard.products.gallery.upload');
    Route::delete('products/gallery/delete/{id}', [DashboardController::class, 'delete_gallery'])->name('dashboard.products.gallery.delete');

    Route::get('transactions', [DashboardController::class, 'transactions'])->name('dashboard.transactions');
    Route::get('transactions/{id}', [DashboardController::class, 'transactions_details'])->name('dashboard.transactions.details');

    Route::put('transactions/{id}', [DashboardController::class, 'transactions_update'])->name('dashboard.transactions.update');

    Route::get('store/settings', [DashboardController::class, 'store_settings'])->name('dashboard.store.settings');
    Route::get('account/settings', [DashboardController::class, 'account_settings'])->name('dashboard.account.settings');
    Route::post('account/settings/{redirect}', [DashboardController::class, 'account_settings_update'])->name('dashboard.account.update');
});

Route::prefix('admin')->middleware('auth', 'admin')->group(function () {
    Route::get('/', [AdminDashboardController::class, 'index'])->name('admin.dashboard');
    Route::resource('category', AdminCategoryController::class);
    Route::resource('user', UserController::class);
    Route::resource('product', ProductController::class);
    Route::resource('product-gallery', ProductGalleryController::class);
    Route::resource('transaction', TransactionContoller::class);
});

Auth::routes();

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'categories';
    protected $guarded = [];

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Alert;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request()->ajax())
        {
            $query = Category::query();

            return Datatables::of($query)
                ->addColumn('action', function($item) {
                return '

                                <form class="d-flex" action="'.route('category.destroy', $item->id).'" method="POST">
                                '.method_field('DELETE') . csrf_field() .'
                                <a class="btn btn-warning mr-1" href="'.route('category.edit', $item->id).'">
                                    Edit
                                </a>
                                <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                ';
            })
            ->editColumn('photo', function($item) {
                return $item->photo ? '<a href="'.asset('photos/'.$item->photo).'" target="_blank"><img src="'. asset('photos/'.$item->photo) .'" class="rounded mt-2 mb-2" style="max-height: 80px;" /></a>' : '';
            })
            ->rawColumns(['action', 'photo'])
            ->make();
        }

        return view('pages.admin.category.index')->with('i');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string',
            'photo' => 'required|image|max:2048|mimes:jpeg,png,jpg,gif,svg',
        ]);
        $slug = Str::slug($request->name);

        $imageName = time().rand(100,999).".".$request->photo->getClientOriginalExtension();

        $request->photo->move(public_path().'/photos', $imageName);
        Category::create([
            'name' => $request->name,
            'photo' =>$imageName,
            'slug' => $slug
        ]);

        alert()->success('Success','Berhasil menambahkan category !')->persistent('Ok');
        return redirect()->route('category.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('pages.admin.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);

        $photo = $request->file('photo');

        // Kalo pas diedit gambar diganti / masukin gambar
        if($photo) {
            $this->validate($request, [
                'name' => 'required|string',
                'photo' => 'image|max:2048|mimes:jpeg,png,jpg,gif,svg',
            ]);

            $slug = Str::slug($request->name);

            $imageName = time().rand(100,999).".".$photo->getClientOriginalExtension();

            $photo->move(public_path().'/photos', $imageName);
            $category->update([
                'name' => $request->name,
                'photo' =>$imageName,
                'slug' => $slug
            ]);

            alert()->success('Success','Berhasil memperbarui category !')->persistent('Ok');
            return redirect()->route('category.index');

        }
            $this->validate($request, [
                'name' => 'required|string',
            ]);

            $slug = Str::slug($request->name);

            $category->update([
                'name' => $request->name,
                'slug' => $slug,
            ]);

            alert()->success('Success','Berhasil memperbarui category !')->persistent('Ok');
            return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        alert()->success('Success','Berhasil menghapus category !')->persistent('Ok');
        return redirect()->route('category.index');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Pagination\Paginator;
class CategoryController extends Controller
{
     /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        Paginator::useBootstrap();
        $categories = Category::all();
        $products = Product::with('galleries')->latest()->paginate(12);


        return view('pages.category', compact('categories', 'products'))->with('i')->with('p');
    }

    public function detail(Request $request, $slug)
    {
        Paginator::useBootstrap();
        $categories = Category::all();
        $category = Category::where('slug', $slug)->firstOrFail();
        $products = Product::with('galleries')->where('categories_id', $category->id)->paginate(12);


        return view('pages.category', compact('categories', 'products'))->with('i')->with('p');
    }
}

resources/views/pages/admin/category/create.blade.php
@extends('layouts.admin')

@section('header')
    <h1>Create New Category</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
        <div class="breadcrumb-item"><a href="{{ route('category.index') }}">Category</a></div>
        <div class="breadcrumb-item active"><a href="{{ route('category.create') }}">Category Create</a></div>
    </div>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
      @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
      @endif
      <div class="card">
        <div class="card-body">
            <form action="{{ route('category.store') }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label" for="nama_category">Nama Category</label>
                            <input type="text" name="name" id="nama_category" class="form-control" required>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label" for="foto_category">Foto Category</label>
                            <input type="file" name="photo" id="foto_category" class="form-control" required>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" id="btn-submit" class="btn btn-success px-5">Save Now</button>
                    </div>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/pages/admin/category/edit.blade.php
@extends('layouts.admin')

@section('header')
    <h1>Create New Category</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
        <div class="breadcrumb-item"><a href="{{ route('category.index') }}">Category</a></div>
        <div class="breadcrumb-item active"><a href="{{ route('category.create') }}">Category Create</a></div>
    </div>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
      @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
      @endif
      <div class="card">
        <div class="card-body">
            <form action="{{ route('category.update', $category->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label" for="nama_category">Nama Category</label>
                            <input type="text" name="name" id="nama_category" class="form-control" value="{{ $category->name }}" required>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label" for="foto_category">Foto Category</label>
                            <input type="file" accept="image/*" name="photo" id="imgInp" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label" for="old_photo">Old Photo</label>
                            <br>
                            <img src="{{ asset('photos/'.$category->photo) }}" id="old_photo" class="rounded mt-2 mb-2" style="max-height: 200px;" alt="photo product">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label" for="blah">Preview New Photo</label>
                            <br>
                            <img src="" id="blah" class="rounded mt-2 mb-2" style="max-height: 200px;" alt="new photo not selected">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" id="btn-submit" class="btn btn-warning px-5">Update Now</button>
                    </div>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('script')
    <script>
        imgInp.onchange = evt => {
            const [file] = imgInp.files
            if (file) {
                blah.src = URL.createObjectURL(file)
            }
        }
    </script>
@endpush

resources/views/pages/admin/category/index.blade.php
@extends('layouts.admin')

@section('header')
    <h1>List Category</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
        <div class="breadcrumb-item active"><a href="{{ route('category.index') }}">Category</a></div>
    </div>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <a href="{{ route('category.create') }}" class="btn btn-primary mb-3">+ Tambah Kategori Baru</a>
          <div class="dropdown-divider"></div>
          <div class="table-responsive">
            <table class="table-hover scroll-horizontal-vertical w-100" id="crudTable">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Nama</th>
                  <th>Foto</th>
                  <th>Slug</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('style')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.25/datatables.min.css"/>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@endpush
@push('script')
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.25/datatables.min.js"></script>
    <script>
        var datatable = $('#crudTable').DataTable({
            processing: true,
            serverSide: true,
            ordering: true,
            ajax: {
                url: '{!! url()->current() !!}',
            },
            columns: [
                { data: 'id', name: 'id' },
                { data: 'name', name: 'name' },
                { data: 'photo', name: 'photo' },
                { data: 'slug', name: 'slug' },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searcable: false,
                    width: '15%'
                },
            ]
        })
    </script>
    @include('sweetalert::alert')
@endpush