routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProductGalleryController;
use App\Http\Controllers\Admin\TransactionContoller;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DetailController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/categories', [CategoryController::class, 'index'])->name('categories');
Route::get('/categories/{id}', [CategoryController::class, 'detail'])->name('categories.detail');

Route::get('/details/{id}', [DetailController::class, 'index'])->name('detail');
Route::post('/details/{id}', [DetailController::class, 'add'])->name('detail.add');

Route::get('/success', [CartController::class, 'success'])->name('success');
Route::get('/register/success', [RegisterController::class, 'success'])->name('register.success');

Route::middleware(['auth'])->group(function () {
    Route::get('/cart', [CartController::class, 'index'])->name('cart');
    Route::delete('/cart/{id}', [CartController::class, 'delete'])->name('cart.delete');

    Route::post('/checkout', [CheckoutController::class, 'process'])->name('checkout');
    Route::post('/checkout/callback', [CheckoutController::class, 'callback'])->name('checkout.callback');
});

Route::prefix('dashboard')->middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('products', [DashboardController::class, 'products'])->name('dashboard.products');
    Route::get('products/create', [DashboardController::class, 'products_create'])->name('dashboard.products.create');
    Route::post('products/store', [DashboardController::class, 'products_store'])->name('dashboard.products.store');
    Route::get('products/{id}', [DashboardController::class, 'products_details'])->name('dashboard.products.details');
    Route::put('products/{id}', [DashboardController::class, 'products_update'])->name('dashboard.products.update');

    Route::post('products/gallery/upload', [DashboardController::class, 'upload_gallery'])->name('dashboard.products.gallery.upload');
    Route::delete('products/gallery/delete/{id}', [DashboardController::class, 'delete_gallery'])->name('dashboard.products.gallery.delete');

    Route::get('transactions', [DashboardController::class, 'transactions'])->name('dashboard.transactions');
    Route::get('transactions/{id}', [DashboardController::class, 'transactions_details'])->name('dashboard.transactions.details');

    Route::put('transactions/{id}', [DashboardController::class, 'transactions_update'])->name('dashboard.transactions.update');

    Route::get('store/settings', [DashboardController::class, 'store_settings'])->name('dashboard.store.settings');
    Route::get('account/settings', [DashboardController::class, 'account_settings'])->name('dashboard.account.settings');
    Route::post('account/settings/{redirect}', [DashboardController::class, 'account_settings_update'])->name('dashboard.account.update');
});

Route::prefix('admin')->middleware('auth', 'admin')->group(function () {
    Route::get('/', [AdminDashboardController::class, 'index'])->name('admin.dashboard');
    Route::resource('category', AdminCategoryController::class);
    Route::resource('user', UserController::class);
    Route::resource('product', ProductController::class);
    Route::resource('product-gallery', ProductGalleryController::class);
    Route::resource('transaction', TransactionContoller::class);
});

Auth::routes();

app/Models/ProductGallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductGallery extends Model
{
    use HasFactory;

    protected $table = 'product_galleries';
    protected $guarded = [];

    public function product()
    {
        return $this->belongsTo(Product::class, 'products_id', 'id');
    }
}

app/Http/Controllers/Admin/ProductGalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Alert;
use App\Http\Requests\Admin\ProductGalleryRequest;
use App\Models\Category;
use App\Models\ProductGallery;
use App\Models\User;
use Yajra\DataTables\Facades\DataTables;

class ProductGalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request()->ajax())
        {
            $query = ProductGallery::with(['product']);

            return Datatables::of($query)
                ->addColumn('action', function($item) {
                return '

                                <form class="d-flex" action="'.route('product-gallery.destroy', $item->id).'" method="POST">
                                '.method_field('DELETE') . csrf_field() .'
                                <a class="btn btn-warning mr-1" href="'.route('product-gallery.edit', $item->id).'">
                                    Edit
                                </a>
                                <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                ';
            })
            ->editColumn('photos', function($item) {
                return $item->photos ? '<a href="'.asset('photos-gallery/'.$item->photos).'" target="_blank"><img src="'. asset('photos-gallery/'.$item->photos) .'" class="rounded mt-2 mb-2" style="max-height: 80px;" /></a>' : '';
            })
            ->rawColumns(['action', 'photos'])
            ->make();
        }

        return view('pages.admin.product-gallery.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::all();
        return view('pages.admin.product-gallery.create', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'photos' => 'required|image|max:2048|mimes:jpeg,png,jpg,gif,svg',
            'products_id' => 'required|exists:products,id'
        ]);

        $imageName = time().rand(100,999).".".$request->photos->getClientOriginalExtension();

        $request->photos->move(public_path().'/photos-gallery', $imageName);
        ProductGallery::create([
            'products_id' => $request->products_id,
            'photos' =>$imageName,
        ]);

        alert()->success('Success','Berhasil menambahkan photo !')->persistent('Ok');
        return redirect()->route('product-gallery.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $products = Product::all();
        $product_gallery = ProductGallery::findOrFail($id);
        return view('pages.admin.product-gallery.edit', compact('products', 'product_gallery'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product_gallery = ProductGallery::findOrFail($id);

        $photo = $request->file('photos');

        // Kalo pas diedit gambar diganti / masukin gambar
        if($photo) {
            $this->validate($request, [
                'photos' => 'required|image|max:2048|mimes:jpeg,png,jpg,gif,svg',
                'products_id' => 'required|exists:products,id'
            ]);

            $imageName = time().rand(100,999).".".$photo->getClientOriginalExtension();

            $photo->move(public_path().'/photos-gallery', $imageName);
            $product_gallery->update([
                'products_id' => $request->products_id,
                'photos' =>$imageName,
            ]);

            alert()->success('Success','Berhasil memperbarui photo !')->persistent('Ok');
            return redirect()->route('product-gallery.index');

        }
            $this->validate($request, [
                'products_id' => 'required|exists:products,id'
            ]);

            $product_gallery->update([
                'products_id' => $request->products_id,
            ]);

            alert()->success('Success','Berhasil memperbarui photo !')->persistent('Ok');
            return redirect()->route('product-gallery.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = ProductGallery::findOrFail($id);
        $photo = public_path('/photos-gallery/').$product->photos;
        if(file_exists($photo))
        {
            @unlink($photo);
        }
        $product->delete();

        alert()->success('Success','Berhasil menghapus product !')->persistent('Ok');
        return redirect()->route('product-gallery.index');
    }
}

resources/views/pages/admin/product-gallery/create.blade.php
@extends('layouts.admin')

@section('header')
    <h1>Create New Product Gallery</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
        <div class="breadcrumb-item"><a href="{{ route('product-gallery.index') }}">Product Gallery</a></div>
        <div class="breadcrumb-item active"><a href="{{ route('product-gallery.create') }}">Product Gallery Create</a></div>
    </div>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
      @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
      @endif
      <div class="card">
        <div class="card-body">
            <form action="{{ route('product-gallery.store') }}" method="POST" enctype="multipart/form-data">
                @csrf

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label" for="products">Product</label>
                            <select name="products_id" id="products" class="form-control">
                                <option value="" selected disabled>Pilih Product</option>
                                @foreach ($products as $product)
                                    <option value="{{ $product->id }}">{{ $product->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label" for="photos">Photo Product</label>
                            <input type="file" name="photos" id="photos" class="form-control" required>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" id="btn-submit" class="btn btn-success px-5">Save Now</button>
                    </div>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('script')
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'editor' );
    </script>
@endpush

resources/views/pages/admin/product-gallery/edit.blade.php
@extends('layouts.admin')

@section('header')
    <h1>Create New Product Gallery</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
        <div class="breadcrumb-item"><a href="{{ route('product-gallery.index') }}">Product Gallery</a></div>
        <div class="breadcrumb-item active"><a href="{{ route('product-gallery.create') }}">Product Gallery Create</a></div>
    </div>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
      @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
      @endif
      <div class="card">
        <div class="card-body">
            <form action="{{ route('product-gallery.update', $product_gallery->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label" for="products">Product</label>
                            <select name="products_id" id="products" class="form-control">
                                <option value="" selected disabled>Pilih Product</option>
                                @foreach ($products as $product)
                                    <option value="{{ $product->id }}" @if($product->id == $product_gallery->product->id) selected @endif>{{ $product->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label" for="photos">Photo Product</label>
                            <input type="file" name="photos" id="photos" class="form-control" onchange="loadFile(event)" required>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label" for="old_photo">Old Photo</label>
                            <br>
                            <img src="{{ asset('photos-gallery/'.$product_gallery->photos) }}" id="old_photo" class="rounded mt-2 mb-2" style="max-height: 200px;" alt="photo product">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="form-label" for="preview_photo">Preview New Photo</label>
                            <br>
                            <img src="" id="preview_photo" class="rounded mt-2 mb-2" style="max-height: 200px;" alt="new photo not selected">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col text-right">
                        <button type="submit" id="btn-submit" class="btn btn-warning px-5">Update Now</button>
                    </div>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('script')
    <script>
        var loadFile = function(event) {
            var reader = new FileReader();
            reader.onload = function(){
                var output = document.getElementById('preview_photo');
                output.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
        };
    </script>
@endpush

resources/views/pages/admin/product-gallery/index.blade.php
@extends('layouts.admin')

@section('header')
    <h1>List Product-Gallery</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
        <div class="breadcrumb-item active"><a href="{{ route('product-gallery.index') }}">Product Gallery</a></div>
    </div>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <a href="{{ route('product-gallery.create') }}" class="btn btn-primary mb-3">+ Tambah Product Gallery Baru</a>
          <div class="dropdown-divider"></div>
          <div class="table-responsive">
            <table class="table-hover scroll-horizontal-vertical w-100" id="crudTable">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Product</th>
                  <th>Photo</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection
@push('style')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.25/datatables.min.css"/>
@endpush
@push('script')
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.25/datatables.min.js"></script>
    <script>
        var datatable = $('#crudTable').DataTable({
            processing: true,
            serverSide: true,
            ordering: true,
            ajax: {
                url: '{!! url()->current() !!}',
            },
            columns: [
                { data: 'id', name: 'id' },
                { data: 'product.name', name: 'product.name' },
                { data: 'photos', name: 'photos' },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searcable: false,
                    width: '15%'
                },
            ]
        })
    </script>
    @include('sweetalert::alert')
@endpush